"""Deterministic ONNX exports for QAT training.

Problem
-------
DeduplicateInitializersPass (inside onnx_program.optimize() / onnxslim) merges
initializers whose (dtype, shape, tobytes) are identical.  When the set of
equal-valued small tensors (scales / zero points) changes between epochs, the
saved models end up with:
    * different initializer counts
    * different val_N names for the same semantic position
    * different shared-reference patterns between Q/DQ nodes

There are two independent sources of the drift:
    1. The Dynamo exporter deduplicates Python-scalar constants by value
       (``constant_farm`` in torch.onnx._internal.exporter._building).
    2. onnxscript's DeduplicateInitializersPass and onnxslim's ``tie_weights``
       merge equal-valued initializers again during optimization.

Usage
-----
    from onnx_canonicalize import export_onnx_program, optimize_onnx_program, slim_onnx_program

    onnx_program = export_onnx_program(model, (x,), dynamo=True)  # no constant sharing
    optimize_onnx_program(onnx_program)                           # no initializer dedup, paired Q/DQ edges
    onnx_program.save(path)
    slim_onnx_program(onnx_program)                               # single slim round, no weight tying
    onnx_program.save(path)

Every stage keeps the same ``onnx_program`` contract, and two epochs with
identical graph topology produce identical initializer lists (count, names,
and per-node references).  Numerical semantics are unchanged.

``canonicalize_initializers`` is kept as an optional fallback (split shared
initializers + rename by graph position) for environments where the upstream
constant sharing cannot be disabled.
"""

from __future__ import annotations

from collections import defaultdict
import re

import onnx
from onnx import TensorProto


def _iter_nodes_topological(graph: onnx.GraphProto) -> list[onnx.NodeProto]:
    """Return graph nodes in deterministic topological order."""
    try:
        return onnx.topological_sort(list(graph.node))
    except Exception:
        # Fall back to file order; only used when the graph is malformed anyway.
        return list(graph.node)


def _collect_uses(
    graph: onnx.GraphProto,
    prefix: tuple[str, ...],
    uses: dict[str, list[tuple[tuple[str, ...], int, int]]],
) -> None:
    """Collect every (graph-path, node-index, input-slot) that references an initializer."""
    nodes = _iter_nodes_topological(graph)
    for node_idx, node in enumerate(nodes):
        for slot, name in enumerate(node.input):
            if name:
                uses[name].append((prefix, node_idx, slot))
        for attr in node.attribute:
            if attr.type == onnx.AttributeProto.GRAPH:
                _collect_uses(attr.g, prefix + (attr.name,), uses)
            elif attr.type == onnx.AttributeProto.GRAPHS:
                for subgraph in attr.graphs:
                    _collect_uses(subgraph, prefix + (attr.name,), uses)


def _canonical_name(prefix: tuple[str, ...], node_idx: int, slot: int) -> str:
    parts = "".join(f"_{p}" for p in prefix)
    return f"init{parts}_{node_idx}_{slot}"


_AUTOGENERATED_NAME = re.compile(r"^val_\d+$")


def _is_autogenerated(name: str) -> bool:
    return bool(_AUTOGENERATED_NAME.match(name))


def _rewrite_references(
    graph: onnx.GraphProto,
    replacements: dict[str, list[str]],
    counts: dict[str, int],
) -> None:
    """Rewrite node inputs (main graph + subgraphs) to the split initializer names."""
    nodes = _iter_nodes_topological(graph)
    for node in nodes:
        new_inputs = []
        for name in node.input:
            if name in counts:
                idx = counts[name]
                counts[name] += 1
                new_inputs.append(replacements[name][idx])
            else:
                new_inputs.append(name)
        del node.input[:]
        node.input.extend(new_inputs)

        for attr in node.attribute:
            if attr.type == onnx.AttributeProto.GRAPH:
                _rewrite_references(attr.g, replacements, counts)
            elif attr.type == onnx.AttributeProto.GRAPHS:
                for subgraph in attr.graphs:
                    _rewrite_references(subgraph, replacements, counts)


def canonicalize_initializers(model: onnx.ModelProto) -> onnx.ModelProto:
    """Split shared initializers and rename every initializer by graph position.

    The model is modified in place and also returned.  It must be applied after
    all other optimizations (torch optimize / onnxslim), as the last step
    before saving.
    """
    graph = model.graph
    initializers = {init.name: init for init in graph.initializer}

    # Initializers that are also graph inputs are left untouched (they may be
    # overridden at runtime and are not subject to dedup).
    input_names = {i.name for i in graph.input}
    splittable = {
        name: init
        for name, init in initializers.items()
        if name not in input_names
    }

    uses: dict[str, list[tuple[tuple[str, ...], int, int]]] = defaultdict(list)
    _collect_uses(graph, (), uses)

    # Assign one canonical name per (initializer, reference) pair.
    replacements: dict[str, list[str]] = {}
    new_initializers: list[onnx.TensorProto] = []

    for name, init in initializers.items():
        refs = uses.get(name, [])
        if name not in splittable:
            # Graph input initializer: keep as-is.
            new_initializers.append(init)
            continue
        if not refs:
            # Unused after optimization: drop deterministically.
            continue

        # Keep meaningful original names (conv1.bias, _frozen_param0, ...) when
        # the initializer is referenced exactly once; auto-generated val_N names
        # and shared initializers are renamed from graph position.
        if len(refs) == 1 and not _is_autogenerated(name):
            canonical_names = [name]
        else:
            canonical_names = [
                _canonical_name(prefix, node_idx, slot)
                for prefix, node_idx, slot in refs
            ]
        replacements[name] = canonical_names
        for canonical_name, (_, _, _) in zip(canonical_names, refs):
            copy = onnx.TensorProto()
            copy.CopyFrom(init)
            copy.name = canonical_name
            new_initializers.append(copy)

    # Rewrite all node references, including subgraphs.
    counts = {name: 0 for name in replacements}
    _rewrite_references(graph, replacements, counts)

    # Deterministic serialization order.
    new_initializers.sort(key=lambda t: t.name)
    del graph.initializer[:]
    graph.initializer.extend(new_initializers)

    onnx.checker.check_model(model)
    return model


def _optimize_ir_without_dedup(
    model,
    *,
    num_iterations: int = 2,
    onnx_shape_inference: bool = True,
    stop_if_no_change: bool = True,
    input_size_limit: int | None = None,
    output_size_limit: int | None = None,
    inline: bool = True,
) -> None:
    """Replicate ``onnxscript.optimizer.optimize_ir`` without initializer dedup.

    The pass list mirrors the installed onnxscript's internal optimizer, with
    ``DeduplicateInitializersPass`` intentionally omitted, so initializers are
    never merged by value.
    """
    import onnx_ir as ir
    import onnx_ir.passes.common as common_passes
    from onnxscript import rewriter
    from onnxscript.optimizer import _constant_folding

    if input_size_limit is None:
        input_size_limit = _constant_folding.DEFAULT_CONSTANT_FOLD_INPUT_SIZE_LIMIT
    if output_size_limit is None:
        output_size_limit = _constant_folding.DEFAULT_CONSTANT_FOLD_OUTPUT_SIZE_LIMIT

    passes = [
        ir.passes.PassManager(
            [
                _constant_folding.FoldConstantsPass(
                    shape_inference=onnx_shape_inference,
                    input_size_limit=input_size_limit,
                    output_size_limit=output_size_limit,
                ),
                rewriter.RewritePass(rewriter._DEFAULT_REWRITE_RULES),
                common_passes.RemoveUnusedNodesPass(),
                common_passes.RemoveUnusedFunctionsPass(),
                common_passes.RemoveUnusedOpsetsPass(),
            ],
            steps=num_iterations,
            early_stop=stop_if_no_change,
        ),
        common_passes.RemoveUnusedNodesPass(),
        common_passes.LiftConstantsToInitializersPass(lift_all_constants=True, size_limit=0),
        common_passes.LiftSubgraphInitializersToMainGraphPass(),
        # DeduplicateInitializersPass intentionally omitted.
        common_passes.CommonSubexpressionEliminationPass(),
    ]
    if inline:
        passes = [common_passes.InlinePass(), *passes]

    optimizer_pass = ir.passes.Sequential(*passes)
    result = optimizer_pass(model)
    assert result.model is model


def _slim_once(
    model: onnx.ModelProto,
    skip_optimizations: tuple[str, ...] = ("weight_tying",),
) -> onnx.ModelProto:
    """Run onnxslim's internal optimization exactly once (no convergence loop).

    ``weight_tying`` (``tie_weights``) is skipped by default because it merges
    equal-valued small initializers — the same cross-epoch drift we are
    removing.  Previous optimization settings are restored afterwards.
    """
    from onnxslim.core import OptimizationSettings, freeze
    from onnxslim.core import optimize as core_optimize
    from onnxslim.core import shape_infer

    previous = {key: getattr(OptimizationSettings, key) for key in OptimizationSettings.keys()}
    OptimizationSettings.reset(list(skip_optimizations))
    freeze(model)
    try:
        slimmed = core_optimize(model)
        try:
            slimmed = shape_infer(slimmed)
        except Exception:
            # Shape inference is best-effort here; the graph is still valid.
            pass
    finally:
        for key, value in previous.items():
            setattr(OptimizationSettings, key, value)
    return slimmed


def pair_qdq_edges(model_proto: onnx.ModelProto) -> onnx.ModelProto:
    """Merge duplicate DequantizeLinear consumers of a shared QuantizeLinear.

    Spec rule 3.4: a ``QuantizeLinear`` output must have exactly one consumer,
    the paired ``DequantizeLinear``; that DQ may then feed many branches.
    pt2e emits one DQ per consumer edge for a shared observed tensor, so a Q at
    a branch point feeds several identical DQs.  For each such Q, keep the
    first DQ (its scale/zero_point must match by name or by value), rewire the
    consumers of the other DQs to it, and drop the redundant DQs.  Q/DQ pairs
    around ops (e.g. MaxPool/Resize) are untouched: every op still sits behind
    its own DQ and in front of its own Q.

    Non-standard shapes (a Q consumed by a non-DQ node, a DQ feeding a graph
    output, mismatched quant params) are left as-is for the spec verifier to
    flag.  Numerical semantics are unchanged: a DQ is deterministic given its
    quant params, so merging identical duplicates is an identity transform.
    """
    from onnx import numpy_helper

    graph = model_proto.graph
    consumers: dict[str, list[onnx.NodeProto]] = defaultdict(list)
    for node in graph.node:
        for inp in node.input:
            consumers[inp].append(node)
    initializers = {i.name: i for i in graph.initializer}
    graph_outputs = {o.name for o in graph.output}

    def same_param(dq_a: onnx.NodeProto, dq_b: onnx.NodeProto, idx: int) -> bool:
        name_a, name_b = dq_a.input[idx], dq_b.input[idx]
        if name_a == name_b:
            return True
        init_a, init_b = initializers.get(name_a), initializers.get(name_b)
        if init_a is None or init_b is None:
            return False
        arr_a, arr_b = numpy_helper.to_array(init_a), numpy_helper.to_array(init_b)
        return (
            init_a.data_type == init_b.data_type
            and arr_a.shape == arr_b.shape
            and arr_a.tobytes() == arr_b.tobytes()
        )

    rewire: dict[str, str] = {}
    dropped: list[onnx.NodeProto] = []
    for node in graph.node:
        if node.op_type != "QuantizeLinear" or not node.output:
            continue
        edges = consumers.get(node.output[0], [])
        dqs = [c for c in edges if c.op_type == "DequantizeLinear"]
        if len(dqs) <= 1 or len(dqs) != len(edges):
            continue
        keep = dqs[0]
        for dq in dqs[1:]:
            if dq.output[0] in graph_outputs:
                continue
            if not (same_param(keep, dq, 1) and same_param(keep, dq, 2)):
                continue
            rewire[dq.output[0]] = keep.output[0]
            dropped.append(dq)
    if not dropped:
        return model_proto

    for node in graph.node:
        for i, inp in enumerate(node.input):
            if inp in rewire:
                node.input[i] = rewire[inp]

    dropped_ids = {id(n) for n in dropped}
    kept_nodes = [n for n in graph.node if id(n) not in dropped_ids]
    del graph.node[:]
    graph.node.extend(kept_nodes)

    still_used = {inp for n in graph.node for inp in n.input} | graph_outputs
    kept_inits = [i for i in graph.initializer if i.name in still_used]
    if len(kept_inits) != len(graph.initializer):
        del graph.initializer[:]
        graph.initializer.extend(kept_inits)

    kept_value_info = [v for v in graph.value_info if v.name not in rewire]
    if len(kept_value_info) != len(graph.value_info):
        del graph.value_info[:]
        graph.value_info.extend(kept_value_info)
    return model_proto


def _deserialize_ir(proto: onnx.ModelProto):
    import onnxscript

    return onnxscript.ir.serde.deserialize_model(proto)


def export_onnx_program(*args, **kwargs):
    """``torch.onnx.export`` wrapper that disables value-based constant sharing.

    The Dynamo exporter deduplicates Python-scalar constants through
    ``torch.onnx._internal.exporter._building._get_or_create_constant`` with a
    ``constant_farm`` keyed by ``(value, dtype)``: two Q/DQ layers whose scales
    happen to be equal at one epoch share the same ``val_N`` Constant, while at
    another epoch they do not.  That sharing is the root cause of the
    cross-epoch initializer drift, so this wrapper bypasses the farm and gives
    every constant its own ONNX Value.

    The upstream internals are private APIs; this wrapper is pinned to the
    installed torch version and should be revisited after upgrading torch.
    """
    import torch
    import torch.onnx._internal.exporter._building as _building

    original = _building._get_or_create_constant

    def _no_shared_constants(constant_farm, arg, dtype, opset):
        # A fresh empty farm per call: same value, different Value.
        return original({}, arg, dtype, opset)

    try:
        _building._get_or_create_constant = _no_shared_constants
        return torch.onnx.export(*args, **kwargs)
    finally:
        _building._get_or_create_constant = original


def optimize_onnx_program(onnx_program):
    """Run the onnxscript internal optimizer without initializer merging.

    Equivalent to ``onnx_program.optimize()`` (onnxscript.optimizer.optimize_ir)
    but with DeduplicateInitializersPass omitted, so equal-valued initializers
    are never merged.  Afterwards ``pair_qdq_edges`` merges duplicate DQ
    consumers of shared Q nodes so the graph satisfies spec rule 3.4 without
    relying on onnxslim.  Returns the same ``onnx_program`` with ``model``
    updated in place; callers keep using ``onnx_program.save(path)``.
    """
    _optimize_ir_without_dedup(onnx_program.model)
    onnx_program.model = _deserialize_ir(pair_qdq_edges(onnx_program.model_proto))
    return onnx_program


def slim_onnx_program(
    onnx_program,
    *,
    skip_optimizations: tuple[str, ...] = ("weight_tying",),
):
    """Run onnxslim's internal optimizer exactly once, without weight tying.

    Equivalent to one round of the public ``slim()`` internals (freeze +
    core.optimize + shape_infer), not the multi-iteration convergence loop.
    ``weight_tying`` (tie_weights) is skipped by default because it merges
    equal-valued small initializers, which is exactly the cross-epoch drift we
    are removing.  Returns the same ``onnx_program`` with ``model`` updated in
    place; callers keep using ``onnx_program.save(path)``.
    """
    proto = onnx_program.model_proto
    slimmed = _slim_once(proto, skip_optimizations)
    onnx_program.model = _deserialize_ir(slimmed)
    return onnx_program


def _compare(path_a: str, path_b: str) -> None:
    a = onnx.load(path_a)
    b = onnx.load(path_b)
    a_orig = onnx.load(path_a)
    b_orig = onnx.load(path_b)
    ca = canonicalize_initializers(a)
    cb = canonicalize_initializers(b)

    onnx.save(ca, path_a.replace(".onnx", "_canonical.onnx"))
    onnx.save(cb, path_b.replace(".onnx", "_canonical.onnx"))

    na = [i.name for i in ca.graph.initializer]
    nb = [i.name for i in cb.graph.initializer]
    ta = [n.op_type for n in ca.graph.node]
    tb = [n.op_type for n in cb.graph.node]

    print(f"{path_a}: {len(na)} initializers")
    print(f"{path_b}: {len(nb)} initializers")
    print(f"initializer names identical: {na == nb}")
    print(f"node topology identical:     {ta == tb}")
    if na != nb:
        print(f"  A only: {sorted(set(na) - set(nb))}")
        print(f"  B only: {sorted(set(nb) - set(na))}")

    # Numeric equivalence check: canonicalized model vs its own original.
    # ORT runs with all graph optimizations disabled so results reflect the
    # graph as written.
    try:
        import numpy as np
        import onnxruntime as ort

        so = ort.SessionOptions()
        so.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
        rng = np.random.default_rng(0)
        for orig, canon, tag in ((a_orig, ca, "A"), (b_orig, cb, "B")):
            sess_orig = ort.InferenceSession(
                orig.SerializeToString(), so, providers=["CPUExecutionProvider"]
            )
            sess_canon = ort.InferenceSession(
                canon.SerializeToString(), so, providers=["CPUExecutionProvider"]
            )
            inputs = {
                i.name: rng.random(
                    tuple(d if isinstance(d, int) and d > 0 else 2 for d in i.shape)
                ).astype(np.float32)
                for i in sess_orig.get_inputs()
            }
            out_orig = sess_orig.run(None, inputs)
            out_canon = sess_canon.run(None, inputs)
            ok = all(
                np.allclose(x, y, atol=1e-6) for x, y in zip(out_orig, out_canon)
            )
            print(f"epoch {tag}: canonicalized outputs == original: {ok}")
    except Exception as exc:  # pragma: no cover - optional check
        print(f"onnxruntime equivalence check skipped: {exc}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) == 3:
        _compare(sys.argv[1], sys.argv[2])
    else:
        print("usage: python onnx_canonicalize.py <model_a.onnx> <model_b.onnx>")
